name: Run Tests

on:
  push:
    branches: ["*"] # すべてのブランチでのpushイベントでトリガー

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.19.0
        with:
          flutter-version: "3.29.2"
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Upload test results
        if: always() # テストが失敗しても結果をアップロード
        uses: actions/upload-artifact@v5
        with:
          name: test-results
          path: |
            .dart_tool/test_results
            build/test_results
          if-no-files-found: ignore # テスト結果ファイルがない場合はエラーにしない
